name: Build

on:
  push:

permissions: {}

jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install linter
        shell: bash
        run: make lint-install
      - name: Run linter
        shell: bash
        run: make lint

  unittest:
    name: Run unit tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run unit tests
        shell: bash
        run: make unittest